---
abstract: 'Calculate edit distance based on insertion, deletion, substitution, and transposition'
author:
  - 'ugexe <ugexe@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::More: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Levenshtein-XS
no_index:
  directory:
    - t
    - xt
    - examples
provides:
  Text::Levenshtein::XS:
    file: lib/Text/Levenshtein/XS.pm
    version: '0.470'
requires:
  perl: '5.008'
resources:
  bugtracker: https://github.com/ugexe/Text--Levenshtein--XS/issues
  homepage: https://github.com/ugexe/Text--Levenshtein--XS
  repository: https://github.com/ugexe/Text--Levenshtein--XS.git
version: '0.470'
x_Dist_Zilla:
  perl:
    version: '5.020000'
  plugins:
    -
      class: Dist::Zilla::Plugin::ReportPhase
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: ReportPhase
      version: '0.03'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: MakeMaker
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Authority
      name: Authority
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::Git::GatherDir
      config:
        Dist::Zilla::Plugin::Git::GatherDir:
          include_untracked: '0'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::GatherDir
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::OurPkgVersion
      name: OurPkgVersion
      version: '0.005001'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::SingleEncoding
              name: '@Default/SingleEncoding'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@Default/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@Default/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@Default/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@Default/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: '@Default/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Legal
              name: '@Default/Legal'
              version: '4.006'
      name: PodWeaver
      version: '4.006'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: PruneCruft
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::GitFmtChanges
      name: GitFmtChanges
      version: '0.005'
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: ManifestSkip
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: Manifest
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::License
      name: License
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmePodInRoot
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeTextInBuild
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: ReadmeHTMLInBuild
      version: '0.142470'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: '1.200003'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: AutoPrereqs
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Prereqs
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereqs
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::PrereqsClean
      name: PrereqsClean
      version: '0.93'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: CheckPrereqsIndexed
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: MetaJSON
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: MetaYAML
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
              version: '5.020'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: MetaProvides::Package
      version: '2.001002'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@TestingMania/PodCoverageTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Test::Version
      name: '@TestingMania/Test::Version'
      version: '0.002004'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@TestingMania/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Meta::JSON
      name: '@TestingMania/Test::CPAN::Meta::JSON'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::MojibakeTests
      name: '@TestingMania/MojibakeTests'
      version: '0.7'
    -
      class: Dist::Zilla::Plugin::Test::Portability
      name: '@TestingMania/Test::Portability'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@TestingMania/PodSyntaxTests'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Test::UnusedVars
      name: '@TestingMania/Test::UnusedVars'
      version: '2.000006'
    -
      class: Dist::Zilla::Plugin::Test::CPAN::Changes
      name: '@TestingMania/Test::CPAN::Changes'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::Test::NoTabs
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          filename: xt/author/no-tabs.t
          finder:
            - ':InstallModules'
            - ':ExecFiles'
            - ':TestFiles'
      name: '@TestingMania/Test::NoTabs'
      version: '0.09'
    -
      class: Dist::Zilla::Plugin::Test::Synopsis
      name: '@TestingMania/Test::Synopsis'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          bail_out_on_fail: '0'
          fail_on_warning: author
          fake_home: '0'
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          needs_display: '0'
          phase: test
          script_finder:
            - ':ExecFiles'
          skips: []
      name: '@TestingMania/Test::Compile'
      version: '2.048'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: RunExtraTests
      version: '0.022'
    -
      class: Dist::Zilla::Plugin::Test::EOL
      name: Test::EOL
      version: '0.12'
    -
      class: Dist::Zilla::Plugin::Test::ReportPrereqs
      name: Test::ReportPrereqs
      version: '0.019'
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: '0.46'
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: ContributorsFromGit
      version: '0.014'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: CopyFilesFromBuild
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::TravisYML
      name: TravisYML
      version: '1.12'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      config:
        Dist::Zilla::Plugin::Git::CommitBuild:
          branch: build/dev
          build_root: ~
          message: 'Development build of v%v (on %b)'
          multiple_inheritance: 0
          release_branch: build/release
          release_message: 'Release build of v%v (on %b)'
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: Git::CommitBuild
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Check
      config:
        Dist::Zilla::Plugin::Git::Check:
          untracked_files: die
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - .travis.yml
            - README.pod
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Check'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      config:
        Dist::Zilla::Plugin::Git::Commit:
          add_files_in: []
          commit_msg: 'Release v%v'
          time_zone: local
        Dist::Zilla::Role::Git::DirtyFiles:
          allow_dirty:
            - dist.ini
            - .travis.yml
            - README.pod
          allow_dirty_match: []
          changelog: Changes
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Commit'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Tag
      config:
        Dist::Zilla::Plugin::Git::Tag:
          branch: ~
          signed: 0
          tag: v0.470
          tag_format: v%v
          tag_message: v%v
          time_zone: local
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Tag'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::Git::Push
      config:
        Dist::Zilla::Plugin::Git::Push:
          push_to:
            - 'origin dev:dev'
            - 'origin build/dev:build/dev'
          remotes_must_exist: 1
        Dist::Zilla::Role::Git::Repo:
          repo_root: .
      name: '@Git/Push'
      version: '2.025'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: GitHub::Update
      version: '0.38'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: TestRelease
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::Travis::TestRelease
      name: Travis::TestRelease
      version: '1.12'
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: '0.07'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.020'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: MetaProvides::Package/AUTOVIV/:InstallModulesPM
      version: '5.020'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '1'
    version: '5.020'
x_authority: cpan:UGEXE
x_contributors:
  - 'Nick <nlogan@gmail.com>'
  - 'ugexe <nlogan@gmail.com>'
